// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3

package types

type AddCategoryReq struct {
	Name        string `json:"name"`
	Type        string `json:"type"`
	Description string `json:"description"`
	Status      int32  `json:"status,optional"`
}

type AddCategoryResp struct {
	Id          uint64 `json:"id"`
	Name        string `json:"name"`
	Type        string `json:"type"`
	Description string `json:"description"`
	Status      int32  `json:"status"`
	CreatedAt   int64  `json:"createdAt"`
	UpdatedAt   int64  `json:"updatedAt"`
	DeletedAt   int64  `json:"-"`
}

type AddPolicyReq struct {
	Rules [][]string `json:"rules"`
}

type AddPropertyReq struct {
	Name         string `json:"name"`
	Description  string `json:"description"`
	Status       int32  `json:"status"`
	Type         string `json:"type"`
	IsSearch     bool   `json:"isSearch"`
	IsRequired   bool   `json:"isRequired"`
	ValidateRule string `json:"validateRule"`
	CategoryId   uint64 `json:"categoryId"`
}

type AddPropertyResp struct {
	Id           uint64 `json:"id"`
	Name         string `json:"name"`
	Description  string `json:"description"`
	Status       int32  `json:"status"`
	Type         string `json:"type"`
	IsSearch     bool   `json:"isSearch"`
	IsRequired   bool   `json:"isRequired"`
	ValidateRule string `json:"validateRule"`
	CategoryId   uint64 `json:"categoryId"`
	CreatedAt    int64  `json:"createdAt"`
	UpdatedAt    int64  `json:"updatedAt"`
	DeletedAt    int64  `json:"-"`
}

type AddRoleReq struct {
	RoleName string `json:"roleName"`
	ParentId uint64 `json:"parentId"`
}

type AddRoleResp struct {
	RoleName  string `json:"roleName"`
	ParentId  uint64 `json:"parentId"`
	CreatedAt int64  `json:"createdAt"`
	UpdatedAt int64  `json:"updatedAt"`
	Id        uint64 `json:"id"`
}

type Api struct {
	Id          uint64 `json:"id"`
	Path        string `json:"path"`
	Method      string `json:"method"`
	ApiGroup    string `json:"apiGroup"`
	Description string `json:"description"`
	CreatedAt   int64  `json:"createdAt"`
	UpdatedAt   int64  `json:"updatedAt"`
	DeletedAt   int64  `json:"-"`
}

type Category struct {
	Id          uint64     `json:"id"`
	Name        string     `json:"name"`
	Type        string     `json:"type"`
	Description string     `json:"description"`
	Status      int32      `json:"status"`
	Properties  []Property `json:"properties"`
	CreatedAt   int64      `json:"createdAt"`
	UpdatedAt   int64      `json:"updatedAt"`
	DeletedAt   int64      `json:"-"`
}

type ChangePasswordReq struct {
	UserId      uint64 `json:"userId,optional"`
	OldPassword string `json:"oldPassword"`
	NewPassword string `json:"newPassword"`
}

type ChangePasswordResp struct {
}

type CreateApiReq struct {
	Path        string `json:"path"`
	Method      string `json:"method"`
	ApiGroup    string `json:"apiGroup"`
	Description string `json:"description"`
}

type CreateApiResp struct {
	Id          uint64 `json:"id"`
	Path        string `json:"path"`
	Method      string `json:"method"`
	ApiGroup    string `json:"apiGroup"`
	Description string `json:"description"`
	CreatedAt   int64  `json:"createdAt"`
	UpdatedAt   int64  `json:"updatedAt"`
	DeletedAt   int64  `json:"-"`
}

type DeleteApiReq struct {
	Id uint64 `path:"id"`
}

type DeleteApiResp struct {
}

type DeleteCategoryReq struct {
	Id uint64 `path:"id"`
}

type DeleteCategoryResp struct {
}

type DeletePropertyReq struct {
	Id uint64 `path:"id"`
}

type DeletePropertyResp struct {
}

type DeleteRoleReq struct {
	RoleId uint64 `path:"id"`
}

type DeleteRoleResp struct {
}

type DeleteUserReq struct {
	UserId uint64 `path:"id"`
}

type DeleteUserResp struct {
}

type LoginReq struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type LoginResp struct {
	Token string `json:"token"`
}

type PolicyInfo struct {
	Method string `json:"method"`
	Path   string `json:"path"`
}

type Property struct {
	Id           uint64 `json:"id"`
	Name         string `json:"name"`
	Description  string `json:"description"`
	Status       int32  `json:"status"`
	Type         string `json:"type"`
	IsSearch     bool   `json:"isSearch"`
	IsRequired   bool   `json:"isRequired"`
	ValidateRule string `json:"validateRule"`
	CategoryId   uint64 `json:"categoryId"`
	CreatedAt    int64  `json:"createdAt"`
	UpdatedAt    int64  `json:"updatedAt"`
	DeletedAt    int64  `json:"-"`
}

type QueryAllApiReq struct {
}

type QueryAllApiResp struct {
	Apis []Api `json:"apis"`
}

type QueryApiDetailReq struct {
	Id uint64 `path:"id"`
}

type QueryApiDetailResp struct {
	Id          uint64 `json:"id"`
	Path        string `json:"path"`
	Method      string `json:"method"`
	ApiGroup    string `json:"apiGroup"`
	Description string `json:"description"`
	CreatedAt   int64  `json:"createdAt"`
	UpdatedAt   int64  `json:"updatedAt"`
	DeletedAt   int64  `json:"-"`
}

type QueryCategoryDetailReq struct {
	Id uint64 `path:"id"`
}

type QueryCategoryDetailResp struct {
	Id          uint64     `json:"id"`
	Name        string     `json:"name"`
	Type        string     `json:"type"`
	Description string     `json:"description"`
	Status      int32      `json:"status"`
	Properties  []Property `json:"properties"`
	CreatedAt   int64      `json:"createdAt"`
	UpdatedAt   int64      `json:"updatedAt"`
	DeletedAt   int64      `json:"-"`
}

type QueryCategoryReq struct {
	Page     int64  `json:"page"`
	PageSize int64  `json:"pageSize"`
	Name     string `json:"name,optional"`
	Type     string `json:"type,optional"`
	Status   int32  `json:"status,optional"`
	OrderBy  string `json:"orderBy,optional"`
}

type QueryCategoryResp struct {
	Total      int64       `json:"total"`
	Categories []*Category `json:"categories"`
	Page       int64       `json:"page"`
	PageSize   int64       `json:"pageSize"`
}

type QueryPropertyDetailReq struct {
	Id uint64 `path:"id"`
}

type QueryPropertyDetailResp struct {
	Id           uint64 `json:"id"`
	Name         string `json:"name"`
	Description  string `json:"description"`
	Status       int32  `json:"status"`
	Type         string `json:"type"`
	IsSearch     bool   `json:"isSearch"`
	IsRequired   bool   `json:"isRequired"`
	ValidateRule string `json:"validateRule"`
	CategoryId   uint64 `json:"categoryId"`
	CreatedAt    int64  `json:"createdAt"`
	UpdatedAt    int64  `json:"updatedAt"`
	DeletedAt    int64  `json:"-"`
}

type QueryPropertyReq struct {
	Page       int64  `json:"page"`
	PageSize   int64  `json:"pageSize"`
	CategoryId uint64 `json:"categoryId"`
	Name       string `json:"name,optional"`
	Type       string `json:"type,optional"`
	Status     int32  `json:"status,optional"`
	OrderBy    string `json:"orderBy,optional"`
}

type QueryPropertyResp struct {
	Total      int64      `json:"total"`
	Properties []Property `json:"properties"`
	Page       int64      `json:"page"`
	PageSize   int64      `json:"pageSize"`
}

type QueryRolePoliciesReq struct {
	RoleId uint64 `path:"roleId"`
}

type QueryRolePoliciesResp struct {
	Rules []*PolicyInfo `json:"rules"`
}

type QuerySelfInfoReq struct {
	Id uint64 `json:"id,optional"`
}

type QuerySelfInfoResp struct {
	User QueryUserDetailResp `json:"user"`
}

type QueryUserDetailReq struct {
	Id uint64 `path:"id"`
}

type QueryUserDetailResp struct {
	Id        uint64 `json:"id"`
	CreatedAt int64  `json:"createdAt"`
	UpdatedAt int64  `json:"updatedAt"`
	DeletedAt int64  `json:"-"`
	Username  string `json:"username"`
	Email     string `json:"email"`
	Phone     string `json:"phone"`
	Avatar    string `json:"avatar"`
	RoleId    uint64 `json:"roleId"`
	Status    int32  `json:"status"`
	Nickname  string `json:"nickname"`
	Gender    int32  `json:"gender"`
	Major     string `json:"major"`
	Grade     string `json:"grade"`
	College   string `json:"college"`
	Realname  string `json:"realname"`
	Class     string `json:"class"`
	Password  string `json:"-"`
}

type QueryUserListReq struct {
	Page     int64  `json:"page"`
	PageSize int64  `json:"pageSize"`
	Username string `json:"username,optional"`
	Email    string `json:"email,optional"`
	Phone    string `json:"phone,optional"`
	Nickname string `json:"nickname,optional"`
	RoleId   uint64 `json:"roleId,optional"`
	Status   int32  `json:"status,optional"`
	Major    string `json:"major,optional"`
	Grade    string `json:"grade,optional"`
	College  string `json:"college,optional"`
	Realname string `json:"realname,optional"`
	Class    string `json:"class,optional"`
	Gender   int32  `json:"gender,optional"`
	OrderBy  string `json:"orderBy,optional"`
}

type QueryUserListResp struct {
	Total    int64                  `json:"total"`
	List     []*QueryUserDetailResp `json:"list"`
	Page     int64                  `json:"page"`
	PageSize int64                  `json:"pageSize"`
}

type RegisterReq struct {
	Username string `json:"username"`
	Password string `json:"password"`
	Email    string `json:"email,optional"`
	Phone    string `json:"phone,optional"`
	Nickname string `json:"nickname,optional"`
	RoleId   uint64 `json:"roleId"`
	Gender   int32  `json:"gender"`
	Major    string `json:"major"`
	Grade    string `json:"grade"`
	College  string `json:"college"`
	Realname string `json:"realname"`
	Class    string `json:"class"`
}

type RegisterResp struct {
	User *QueryUserDetailResp `json:"user"`
}

type ResetPasswordReq struct {
	UserId uint64 `json:"userId"`
}

type ResetPasswordResp struct {
}

type RoleTree struct {
	RoleName  string      `json:"roleName"`
	ParentId  uint64      `json:"parentId"`
	CreatedAt int64       `json:"createdAt"`
	UpdatedAt int64       `json:"updatedAt"`
	Id        uint64      `json:"id"`
	Children  []*RoleTree `json:"children"`
}

type RoleTreeReq struct {
	Page     int64 `json:"page"`
	PageSize int64 `json:"pageSize"`
}

type RoleTreeResp struct {
	Roles    []*RoleTree `json:"roles"`
	Total    int64       `json:"total"`
	Page     int64       `json:"page"`
	PageSize int64       `json:"pageSize"`
}

type SetRoleInfoReq struct {
	RoleId   uint64 `json:"roleId"`
	RoleName string `json:"roleName"`
}

type SetRoleInfoResp struct {
}

type SetRolePoliciesReq struct {
	RoleId uint64       `json:"roleId"`
	Rules  []PolicyInfo `json:"rules"`
}

type SetRolePoliciesResp struct {
}

type SetSelfInfoReq struct {
	Id       uint64 `json:"id,optional"`
	Username string `json:"username"`
	Email    string `json:"email"`
	Phone    string `json:"phone"`
	Avatar   string `json:"avatar"`
	RoleId   uint64 `json:"roleId"`
	Status   int32  `json:"status"`
	Nickname string `json:"nickname"`
	Gender   int32  `json:"gender"`
	Major    string `json:"major"`
	Grade    string `json:"grade"`
	College  string `json:"college"`
	Realname string `json:"realname"`
	Class    string `json:"class"`
}

type SetSelfInfoResp struct {
}

type SetUserInfoReq struct {
	Id       uint64 `json:"id"`
	Username string `json:"username"`
	Email    string `json:"email"`
	Phone    string `json:"phone"`
	Avatar   string `json:"avatar"`
	RoleId   uint64 `json:"roleId"`
	Status   int32  `json:"status"`
	Nickname string `json:"nickname"`
	Gender   int32  `json:"gender"`
	Major    string `json:"major"`
	Grade    string `json:"grade"`
	College  string `json:"college"`
	Realname string `json:"realname"`
	Class    string `json:"class"`
}

type SetUserInfoResp struct {
}

type SetUserRoleReq struct {
	UserId  uint64   `json:"userId"`
	RoleIds []uint64 `json:"roleIds"`
}

type SetUserRoleResp struct {
}

type UpdateApiReq struct {
	Id          uint64 `json:"id"`
	Path        string `json:"path"`
	Method      string `json:"method"`
	ApiGroup    string `json:"apiGroup"`
	Description string `json:"description"`
}

type UpdateApiResp struct {
	Id          uint64 `json:"id"`
	Path        string `json:"path"`
	Method      string `json:"method"`
	ApiGroup    string `json:"apiGroup"`
	Description string `json:"description"`
	CreatedAt   int64  `json:"createdAt"`
	UpdatedAt   int64  `json:"updatedAt"`
	DeletedAt   int64  `json:"-"`
}

type UpdateCategoryReq struct {
	Id          uint64 `json:"id"`
	Name        string `json:"name"`
	Type        string `json:"type"`
	Description string `json:"description"`
	Status      int32  `json:"status"`
}

type UpdateCategoryResp struct {
	Id          uint64 `json:"id"`
	Name        string `json:"name"`
	Type        string `json:"type"`
	Description string `json:"description"`
	Status      int32  `json:"status"`
	CreatedAt   int64  `json:"createdAt"`
	UpdatedAt   int64  `json:"updatedAt"`
	DeletedAt   int64  `json:"-"`
}

type UpdatePropertyReq struct {
	Id           uint64 `json:"id"`
	Name         string `json:"name"`
	Description  string `json:"description"`
	Status       int32  `json:"status"`
	Type         string `json:"type"`
	IsSearch     bool   `json:"isSearch"`
	IsRequired   bool   `json:"isRequired"`
	ValidateRule string `json:"validateRule"`
	CategoryId   uint64 `json:"categoryId"`
}

type UpdatePropertyResp struct {
	Id           uint64 `json:"id"`
	Name         string `json:"name"`
	Description  string `json:"description"`
	Status       int32  `json:"status"`
	Type         string `json:"type"`
	IsSearch     bool   `json:"isSearch"`
	IsRequired   bool   `json:"isRequired"`
	ValidateRule string `json:"validateRule"`
	CategoryId   uint64 `json:"categoryId"`
	CreatedAt    int64  `json:"createdAt"`
	UpdatedAt    int64  `json:"updatedAt"`
	DeletedAt    int64  `json:"-"`
}
