// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3

package types

type AddPolicyReq struct {
	Rules [][]string `json:"rules"`
}

type AddRoleReq struct {
	RoleName string `json:"roleName"`
	ParentId uint64 `json:"parentId"`
}

type AddRoleResp struct {
	RoleName  string `json:"roleName"`
	ParentId  uint64 `json:"parentId"`
	CreatedAt int64  `json:"createdAt"`
	UpdatedAt int64  `json:"updatedAt"`
	Id        uint64 `json:"id"`
}

type ChangePasswordReq struct {
	UserId      uint64 `json:"userId,optional"`
	OldPassword string `json:"oldPassword"`
	NewPassword string `json:"newPassword"`
}

type ChangePasswordResp struct {
}

type DeleteRoleReq struct {
	RoleId uint64 `path:"id"`
}

type DeleteRoleResp struct {
}

type DeleteUserReq struct {
	UserId uint64 `path:"id"`
}

type DeleteUserResp struct {
}

type LoginReq struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type LoginResp struct {
	Token string `json:"token"`
}

type QuerySelfInfoReq struct {
	Id uint64 `json:"id,optional"`
}

type QuerySelfInfoResp struct {
	User QueryUserDetailResp `json:"user"`
}

type QueryUserDetailReq struct {
	Id uint64 `path:"id"`
}

type QueryUserDetailResp struct {
	Id        uint64 `json:"id"`
	CreatedAt int64  `json:"createdAt"`
	UpdatedAt int64  `json:"updatedAt"`
	DeletedAt int64  `json:"-"`
	Username  string `json:"username"`
	Email     string `json:"email"`
	Phone     string `json:"phone"`
	Avatar    string `json:"avatar"`
	RoleId    uint64 `json:"roleId"`
	Status    int32  `json:"status"`
	Nickname  string `json:"nickname"`
	Gender    int32  `json:"gender"`
	Major     string `json:"major"`
	Grade     string `json:"grade"`
	College   string `json:"college"`
	Realname  string `json:"realname"`
	Class     string `json:"class"`
	Password  string `json:"-"`
}

type QueryUserListReq struct {
	Page     int64  `json:"page"`
	PageSize int64  `json:"pageSize"`
	Username string `json:"username,optional"`
	Email    string `json:"email,optional"`
	Phone    string `json:"phone,optional"`
	Nickname string `json:"nickname,optional"`
	RoleId   uint64 `json:"roleId,optional"`
	Status   int32  `json:"status,optional"`
	Major    string `json:"major,optional"`
	Grade    string `json:"grade,optional"`
	College  string `json:"college,optional"`
	Realname string `json:"realname,optional"`
	Class    string `json:"class,optional"`
	Gender   int32  `json:"gender,optional"`
	OrderBy  string `json:"orderBy,optional"`
}

type QueryUserListResp struct {
	Total    int64                  `json:"total"`
	List     []*QueryUserDetailResp `json:"list"`
	Page     int64                  `json:"page"`
	PageSize int64                  `json:"pageSize"`
}

type RegisterReq struct {
	Username string `json:"username"`
	Password string `json:"password"`
	Email    string `json:"email,optional"`
	Phone    string `json:"phone,optional"`
	Nickname string `json:"nickname,optional"`
	RoleId   uint64 `json:"roleId"`
	Gender   int32  `json:"gender"`
	Major    string `json:"major"`
	Grade    string `json:"grade"`
	College  string `json:"college"`
	Realname string `json:"realname"`
	Class    string `json:"class"`
}

type RegisterResp struct {
	User *QueryUserDetailResp `json:"user"`
}

type ResetPasswordReq struct {
	UserId uint64 `json:"userId"`
}

type ResetPasswordResp struct {
}

type RoleTree struct {
	RoleName  string      `json:"roleName"`
	ParentId  uint64      `json:"parentId"`
	CreatedAt int64       `json:"createdAt"`
	UpdatedAt int64       `json:"updatedAt"`
	Id        uint64      `json:"id"`
	Children  []*RoleTree `json:"children"`
}

type RoleTreeReq struct {
	Page     int64 `json:"page"`
	PageSize int64 `json:"pageSize"`
}

type RoleTreeResp struct {
	Roles    []*RoleTree `json:"roles"`
	Total    int64       `json:"total"`
	Page     int64       `json:"page"`
	PageSize int64       `json:"pageSize"`
}

type SetRoleInfoReq struct {
	RoleId   uint64 `json:"roleId"`
	RoleName string `json:"roleName"`
	ParentId uint64 `json:"parentId"`
}

type SetRoleInfoResp struct {
}

type SetSelfInfoReq struct {
	Id       uint64 `json:"id,optional"`
	Username string `json:"username"`
	Email    string `json:"email"`
	Phone    string `json:"phone"`
	Avatar   string `json:"avatar"`
	RoleId   uint64 `json:"roleId"`
	Status   int32  `json:"status"`
	Nickname string `json:"nickname"`
	Gender   int32  `json:"gender"`
	Major    string `json:"major"`
	Grade    string `json:"grade"`
	College  string `json:"college"`
	Realname string `json:"realname"`
	Class    string `json:"class"`
}

type SetSelfInfoResp struct {
}

type SetUserInfoReq struct {
	Id       uint64 `json:"id"`
	Username string `json:"username"`
	Email    string `json:"email"`
	Phone    string `json:"phone"`
	Avatar   string `json:"avatar"`
	RoleId   uint64 `json:"roleId"`
	Status   int32  `json:"status"`
	Nickname string `json:"nickname"`
	Gender   int32  `json:"gender"`
	Major    string `json:"major"`
	Grade    string `json:"grade"`
	College  string `json:"college"`
	Realname string `json:"realname"`
	Class    string `json:"class"`
}

type SetUserInfoResp struct {
}

type SetUserRoleReq struct {
	UserId  uint64   `json:"userId"`
	RoleIds []uint64 `json:"roleIds"`
}

type SetUserRoleResp struct {
}
