// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3

package handler

import (
	"github.com/bearllflee/scholar-track/api/internal/handler/achievement"
	"github.com/bearllflee/scholar-track/api/internal/handler/api"
	"github.com/bearllflee/scholar-track/api/internal/handler/casbin"
	"github.com/bearllflee/scholar-track/api/internal/handler/dictionary"
	dictionary_detail "github.com/bearllflee/scholar-track/api/internal/handler/dictionary_detail"
	"github.com/bearllflee/scholar-track/api/internal/handler/file"
	"github.com/bearllflee/scholar-track/api/internal/handler/menu"
	"github.com/bearllflee/scholar-track/api/internal/handler/role"
	"github.com/bearllflee/scholar-track/api/internal/handler/user"
	"github.com/bearllflee/scholar-track/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	achievement.RegisterAchievementRoutes(server, serverCtx)
	api.RegisterApiRoutes(server, serverCtx)
	casbin.RegisterCasbinRoutes(server, serverCtx)
	dictionary.RegisterDictionaryRoutes(server, serverCtx)
	dictionary_detail.RegisterDictionaryDetailRoutes(server, serverCtx)
	file.RegisterFileRoutes(server, serverCtx)
	menu.RegisterMenuRoutes(server, serverCtx)
	role.RegisterRoleRoutes(server, serverCtx)
	user.RegisterUserRoutes(server, serverCtx)
}
