// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3

package handler

import (
	"net/http"

	casbin "github.com/bearllflee/scholar-track/api/internal/handler/casbin"
	role "github.com/bearllflee/scholar-track/api/internal/handler/role"
	user "github.com/bearllflee/scholar-track/api/internal/handler/user"
	"github.com/bearllflee/scholar-track/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/casbin/addPolicies",
				Handler: casbin.AddPoliciesHandler(serverCtx),
			},
		},
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/role/add",
				Handler: role.AddRoleHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/role/tree",
				Handler: role.RoleTreeHandler(serverCtx),
			},
		},
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/user/:id",
				Handler: user.QueryUserDetailHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/user/:id",
				Handler: user.DeleteUserHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/user/changePassword",
				Handler: user.ChangePasswordHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/user/list",
				Handler: user.QueryUserListHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/user/login",
				Handler: user.LoginHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/user/register",
				Handler: user.RegisterHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/user/resetPassword",
				Handler: user.ResetPasswordHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/user/selfInfo",
				Handler: user.QuerySelfInfoHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/user/setSelfInfo",
				Handler: user.SetSelfInfoHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/user/setUserInfo",
				Handler: user.SetUserInfoHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/user/setUserRole",
				Handler: user.SetUserRoleHandler(serverCtx),
			},
		},
	)
}
