// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3
// Source: achieve.proto

package achieveclient

import (
	"context"

	"github.com/bearllflee/scholar-track/rpc/achieve/achieve"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	Request  = achieve.Request
	Response = achieve.Response

	Achieve interface {
		Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
	}

	defaultAchieve struct {
		cli zrpc.Client
	}
)

func NewAchieve(cli zrpc.Client) Achieve {
	return &defaultAchieve{
		cli: cli,
	}
}

func (m *defaultAchieve) Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	client := achieve.NewAchieveClient(m.cli.Conn())
	return client.Ping(ctx, in, opts...)
}
