// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3
// Source: achieve.proto

package server

import (
	"context"

	"github.com/bearllflee/scholar-track/rpc/achieve/achieve"
	"github.com/bearllflee/scholar-track/rpc/achieve/internal/logic"
	"github.com/bearllflee/scholar-track/rpc/achieve/internal/svc"
)

type AchieveServer struct {
	svcCtx *svc.ServiceContext
	achieve.UnimplementedAchieveServer
}

func NewAchieveServer(svcCtx *svc.ServiceContext) *AchieveServer {
	return &AchieveServer{
		svcCtx: svcCtx,
	}
}

func (s *AchieveServer) Ping(ctx context.Context, in *achieve.Request) (*achieve.Response, error) {
	l := logic.NewPingLogic(ctx, s.svcCtx)
	return l.Ping(in)
}
