// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3
// Source: system.proto

package casbin

import (
	"context"

	"github.com/bearllflee/scholar-track/rpc/system/system"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AddPolicyReq           = system.AddPolicyReq
	AddPolicyResp          = system.AddPolicyResp
	AddRoleReq             = system.AddRoleReq
	AddRoleResp            = system.AddRoleResp
	ChangePasswordReq      = system.ChangePasswordReq
	ChangePasswordResp     = system.ChangePasswordResp
	DeleteRoleReq          = system.DeleteRoleReq
	DeleteRoleResp         = system.DeleteRoleResp
	DeleteUserReq          = system.DeleteUserReq
	DeleteUserResp         = system.DeleteUserResp
	EnforceReq             = system.EnforceReq
	EnforceResp            = system.EnforceResp
	FindUserByUsernameReq  = system.FindUserByUsernameReq
	FindUserByUsernameResp = system.FindUserByUsernameResp
	QuerySelfInfoReq       = system.QuerySelfInfoReq
	QuerySelfInfoResp      = system.QuerySelfInfoResp
	QueryUserDetailReq     = system.QueryUserDetailReq
	QueryUserDetailResp    = system.QueryUserDetailResp
	QueryUserListReq       = system.QueryUserListReq
	QueryUserListResp      = system.QueryUserListResp
	RegisterReq            = system.RegisterReq
	RegisterResp           = system.RegisterResp
	ResetPasswordReq       = system.ResetPasswordReq
	ResetPasswordResp      = system.ResetPasswordResp
	RoleResp               = system.RoleResp
	RoleTreeListResp       = system.RoleTreeListResp
	RoleTreeReq            = system.RoleTreeReq
	RoleTreeResp           = system.RoleTreeResp
	Rule                   = system.Rule
	SetSelfInfoReq         = system.SetSelfInfoReq
	SetSelfInfoResp        = system.SetSelfInfoResp
	SetUserInfoReq         = system.SetUserInfoReq
	SetUserInfoResp        = system.SetUserInfoResp
	SetUserRoleReq         = system.SetUserRoleReq
	SetUserRoleResp        = system.SetUserRoleResp
	UpdateRoleReq          = system.UpdateRoleReq
	UpdateRoleResp         = system.UpdateRoleResp

	Casbin interface {
		AddPolicy(ctx context.Context, in *AddPolicyReq, opts ...grpc.CallOption) (*AddPolicyResp, error)
		Enforce(ctx context.Context, in *EnforceReq, opts ...grpc.CallOption) (*EnforceResp, error)
	}

	defaultCasbin struct {
		cli zrpc.Client
	}
)

func NewCasbin(cli zrpc.Client) Casbin {
	return &defaultCasbin{
		cli: cli,
	}
}

func (m *defaultCasbin) AddPolicy(ctx context.Context, in *AddPolicyReq, opts ...grpc.CallOption) (*AddPolicyResp, error) {
	client := system.NewCasbinClient(m.cli.Conn())
	return client.AddPolicy(ctx, in, opts...)
}

func (m *defaultCasbin) Enforce(ctx context.Context, in *EnforceReq, opts ...grpc.CallOption) (*EnforceResp, error) {
	client := system.NewCasbinClient(m.cli.Conn())
	return client.Enforce(ctx, in, opts...)
}
